### ISSUE TITLE
Dados duplicados no JSON de controladores

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1004]
O @pauloFernandes identificou que ao fazer o Serialize de vários controladores, o map de endereços (campo `enderecosMap` no `ControladorCustomSerializer`) não era limpado a cada controlador, e como resultado o campo `todosEnderecos` do controlador 2 possuía todos os endereços do controlador 2 e do controlador 1. 
É necessário verificar se isso não está ocorrendo com os outros dados que são colocados no json.

**Comment by pauloFernandes** [comment]
É necessário propagar a correção para as demais rotas de controladores.
