### ISSUE TITLE
Bug em Planos - Erro quando excluo um estágio

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1008]
Meu controlador possui um anel com 4 estágios e o outro com apenas 2. Quando entro em planos, ao excluir o estágio quatro e selecionar o modo de operação "Atuado"o sistema apresenta o erro abaixo. 

![image](https://cloud.githubusercontent.com/assets/505372/18963967/54fdaa88-864d-11e6-82e0-6554f9bbf80d.png)

**Comment by leonardoherbert** [comment]
Feito uma solução temporaria. Temos que achar um solução definitiva para esse problema.
