### ISSUE TITLE
Controlador não passa para estado "Configurado"

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1015]
Cadastrei um novo controlador, passando pelo wizard inteiro até o final. Depois de cadastrado somente o botão de configurar o controlador ficou ativo para mim. Verifiquei na API, e vi que o controlador não ficou "configurado" por conta dos seguintes erros:
![screen shot 2016-09-29 at 21 45 29](https://cloud.githubusercontent.com/assets/194442/18977136/2f205f5e-868e-11e6-8680-5b756b6c92ec.png)

Porém, o controlador criado tem todos os dados (eu cadastrei ele através do wizard, então ele passou em todas as validações).

Controlador:
![screen shot 2016-09-29 at 21 47 32](https://cloud.githubusercontent.com/assets/194442/18977164/61b943e0-868e-11e6-8f00-2130b0a433c4.png)

Anel:
![screen shot 2016-09-29 at 21 48 15](https://cloud.githubusercontent.com/assets/194442/18977174/74ad9fa0-868e-11e6-9d8c-c67276510f9e.png)

A minha humilde opinião é que o Ebean não está retornando os endereços do banco, e a validação está falhando.

**Comment by ppires** [comment]
Liguei o computador no dia seguinte e o problema tinha sumido, provavelmente o ebean devia estar cansado ontem à noite.

**Comment by ppires** [comment]
Reabri pois o problema ainda está ocorrendo intermitentemente.

**Comment by ppires** [comment]
Ocorreu novamente comigo. Na imagem abaixo os dois controladores estão configurados.
![screen shot 2016-09-30 at 19 50 32](https://cloud.githubusercontent.com/assets/194442/19009151/3a142bb6-8747-11e6-835f-e6722e315dac.png)

Pode ser que tenha alguma coisa a ver com o número de anéis. O @JuarezLustosa teve um problema no cucumber com o endereço do controlador confundir com o endereço do segundo anel, e o controlador que está com problema tem 2 anéis. O controlador OK tem somente 1.

**Comment by JuarezLustosa** [comment]
@ppires Ainda Continua acontecendo mesmo com os gets de endereço que fizemos. Tenho uma suposição que isso começou acontecer  depois que atualizamos o scala para 13.12

**Comment by ppires** [comment]
@JuarezLustosa foi o sbt q foi atualizado para o 0.13.12, mas podemos fazer o teste. Ele foi atualizado para tentar resolver o problema do travis falhando, como o problema já foi resolvido, você pode tentar voltar ele pro 0.13.11 e ver se resolve. É só alterar o `influunt-api/project/build.properties`.

Apesar de quê isso parece pra mim mais uma coisa do banco de dados do que do sbt. Está acontecendo comigo de novo agora, e eu tenho mais de um controlador cadastrado. Acho que pode ter a ver com o número de controladores.

**Comment by JuarezLustosa** [comment]
@ppires é era o sbt que queria falar, vou testar aqui.

**Comment by JuarezLustosa** [comment]
@ppires Voltei para 13.11 e funcionou aqui.

**Comment by ppires** [comment]
Boa! Se o problema não acontecer mais até segunda feira no final do dia acho que a gente pode fechar essa issue!

**Comment by ppires** [comment]
Estava acontecendo comigo agora, voltei pra 0.13.11 e o problema continuou... 😞

**Comment by JuarezLustosa** [comment]
Pois é voltou comigo também não era isso, estou pesquisando aqui para ver se acho o que é 😢
