### ISSUE TITLE
Bug no Wizard cadastro de detectores

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1023]
Quando você está cadastrando um controlador com mais de 9 estágios, na parte de detetores vou selecionando-os em seus respectivos estágio, porém a partir do nono, quando seleciono o detector ele apaga o primeiro que ja tinha selecionado, como está na figura. 

![image](https://cloud.githubusercontent.com/assets/505372/19000977/afdf6a30-871b-11e6-8b9d-b081d9cc75b3.png)

**Comment by leonardoherbert** [comment]
Comportamento normal do sistema, caso seja preenchido outro detector em um estagio que já tinha um detector o sistema limpa a associação anterior
