### ISSUE TITLE
Não consigo salvar plano coordenado com estágio dispensável

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1257]
Tentei criar um plano no modo coordenado com estágio dispensável, mas deu erro de validação, dizendo que o `estagioQueRecebeEstagioDispensavel` não pode ficar em branco, mas o `estagioQueRecebeEstagioDispensavel` foi enviado para o servidor. 
O `estagioQueRecebeEstagioDispensavel` é um `EstagioPlano`, e no JSON enviado p/ o servidor dá pra ver que o `idJson` não é de nenhum `EstagioPlano`. Conferi no JSON, o `idJson` enviado é de um estágio, não de um estágio plano.
![screen shot 2016-10-26 at 19 30 15](https://cloud.githubusercontent.com/assets/194442/19746009/2cae8e64-9bb3-11e6-91da-e74bd107482d.png)

**Comment by pauloFernandes** [comment]
@ppires: Quando o usuário marca o checkbox de **"estágio dispensável"** porém não seleciona nenhum **"ESTÁGIO QUE RECEBE TEMPO DO ESTÁGIO DISPENSÁVEL"**, o sistema apresenta esta mesma mensagem. Pode ser este seu caso.

Sugiro que alteremos o sistema para enviar uma mensagem mais clara, do tipo "Este estágio dispoensável precisa ter um estágio que recebe o tempo do estágio dispensável".

Este caso somente deverá ocorrer com os planos no modo **coordenado**

**Comment by ppires** [comment]
@pauloFernandes eu selecionei o "ESTÁGIO QUE RECEBE TEMPO DO ESTÁGIO DISPENSÁVEL", dá pra ver no console que ele foi enviado para o servidor. Porém, o `idJson` do "ESTÁGIO QUE RECEBE TEMPO DO ESTÁGIO DISPENSÁVEL" foi um idJson de `Estagio`, e o estagio que recebe é um `EstagioPlano`
