### ISSUE TITLE
Erro atraso de grupo

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1279]
O Vincenzo enviou um problema com o atraso de grupo:

> Segue problema encontrado no atraso de grupo (tabela de cores) e segue diagramas de como está e como deveria ficar
> ![screen shot 2016-10-28 at 11 57 15](https://cloud.githubusercontent.com/assets/194442/19808943/c71547b0-9d05-11e6-9256-fe6000365b94.png)
> ![screen shot 2016-10-28 at 11 57 26](https://cloud.githubusercontent.com/assets/194442/19808948/ce640006-9d05-11e6-8c91-af6725ea4492.png)
> ![screen shot 2016-10-28 at 11 57 38](https://cloud.githubusercontent.com/assets/194442/19808952/d4f86c36-9d05-11e6-847a-c96ae3b23e1c.png)

**Comment by leonardoherbert** [comment]
O sistema não faz atraso de grupo automatico, temos que implementar
