### ISSUE TITLE
Bug ao pesquisar na listagem de auditoria

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1281]
Ao realizar a pesquisa na listagem de auditoria usando a opção igual, o sistema apresenta erro 

![captura de tela 2016-10-28 as 14 24 06](https://cloud.githubusercontent.com/assets/505372/19813848/46729134-9d1a-11e6-9114-f7eef159bc8e.png)

obs: já deixei o teste de aceitação para isso pronto no arquivo pesquisas.feature, ele está comentado.

**Comment by leonardoherbert** [comment]
Por enquanto pode remover o acesso a essa tela. Depois iremos decidir como iremos tratar essa tela, por enquanto não tem função para o pessoal.
