### ISSUE TITLE
Relatório de status dos controladores

### ISSUE THREAD

**Issue by pauloFernandes** [influunt/influunt#1304]
- Status dos controladores: uma "fotografia" do instante atual dos controladores -> o operador utiliza este relatório para saber o status da rua
      - filtros: subárea, agrupamento
      - campos: dados: falha, modo, imposição de plano e modo manual, plano

**Comment by nathanraro** [comment]
![relatorio status](https://cloud.githubusercontent.com/assets/19826047/20326542/6965f212-ab70-11e6-9a2f-9089fcffe4a1.jpg)
