### ISSUE TITLE
Listar falhas

### ISSUE THREAD

**Issue by pauloFernandes** [influunt/influunt#1306]
- listar falhas
      - filtros: subárea, agrupamento, tipo de falha
      - campos: numero do cruzamento, endereco, tipo de falha (amarelo intermintente, apagado, sem comunicação, falha de entreverdes, etc)

**Comment by leonardoherbert** [comment]
![relatorio_falhas](https://cloud.githubusercontent.com/assets/1890706/20350039/341f0ab0-abf4-11e6-8715-91557a657bd4.jpg)
