### ISSUE TITLE
tabela horaria

### ISSUE THREAD

**Issue by pauloFernandes** [influunt/influunt#1307]
- tabela horaria: lista de trocas de planos em determinado instante da tabela horária
      - filtro: data (default: do dia), controlador
      - campos: horário, plano, numero do plano, modo do plano, subárea

**Comment by leonardoherbert** [comment]
![image](https://cloud.githubusercontent.com/assets/1890706/20325131/77778f6a-ab6a-11e6-9d7e-332a126ab065.png)
