### ISSUE TITLE
Tela de impor configuracao

### ISSUE THREAD

**Issue by rodrigosol** [influunt/influunt#1333]

**Comment by nathanraro** [comment]
PSD está no Drive!

![facilidades - impor modo](https://cloud.githubusercontent.com/assets/19826047/20323592/981a26b6-ab64-11e6-9527-e61ece5f1900.jpg)
![facilidades - impor plano](https://cloud.githubusercontent.com/assets/19826047/20323591/9819501a-ab64-11e6-9b3d-5550ab1f9880.jpg)
![facilidades - sincronizar](https://cloud.githubusercontent.com/assets/19826047/20323594/981da6b0-ab64-11e6-9fd6-2a1b4d7d9705.jpg)
![facilidades](https://cloud.githubusercontent.com/assets/19826047/20323593/981c819a-ab64-11e6-9c6a-93928b47e291.jpg)
