### ISSUE TITLE
Sugestão de Ajuste css para erros em  ASSOCIAÇÃO ESTÁGIO X GRUPO SEMAFÓRICO

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1362]
badge-danger dos grupos associados está muito proximo e desalinhado, dificultando a visualização de qual grupo o erro pertence. Sugiro um melhor alinhamento .
![captura de tela 2016-11-03 as 14 52 51](https://cloud.githubusercontent.com/assets/505372/19976158/c5ae08ec-a1d5-11e6-9fe2-f7bf338dc42e.png)

**Comment by dantemarchi** [comment]
![screen shot 2016-11-17 at 15 43 26](https://cloud.githubusercontent.com/assets/1928821/20400638/b1a5d764-acdc-11e6-98d3-635c40846c1d.png)
