### ISSUE TITLE
Limitar ou truncate ao editar o nome do plano

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1368]
![Uploading Captura de Tela 2016-11-03 às 17.05.56.png…]()

**Comment by leonardoherbert** [comment]
@JuarezLustosa o print da tela não carregou, poderia inserir novamente para que possamos verificar?

Fiz uma descrição e na minha tela gerou duas linhas, mas não quebrou.

![image](https://cloud.githubusercontent.com/assets/1890706/20054939/155c7728-a4c6-11e6-9ac7-1ca42bb053f4.png)

**Comment by JuarezLustosa** [comment]
@leonardoherbert O erro acontece quando não há espaço no titulo.
![captura de tela 2016-11-07 as 17 02 54](https://cloud.githubusercontent.com/assets/505372/20071590/2f0f878c-a50c-11e6-857e-553abaaac86d.png)

**Comment by leonardoherbert** [comment]
Acho que não deveríamos tratar isso, pois é uma escrita errada não existe uma única palavra desse tamanho. 

@pauloFernandes tem alguma solução fácil para esse problema?

@JuarezLustosa, @ppires deve ter esse problema em outros lugares também, o que você? Devemos tratar mesmo assim?

**Comment by pauloFernandes** [comment]
@leonardoherbert: uma solução para o caso seria truncar o texto https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/. Para o nosso caso:

```css
.desc-plano {
  width: 150px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

Este bloco resolve o problema apresentado pelo @JuarezLustosa, mas compromete o formato que o @leonardoherbert apresentou, onde um texto escrito da forma correta faz quebra linha.

<img width="298" alt="screen shot 2016-11-08 at 09 52 47" src="https://cloud.githubusercontent.com/assets/2263368/20098097/27109cb4-a599-11e6-9056-f37da579dc0a.png">

**Comment by JuarezLustosa** [comment]
@leonardoherbert Concordo com você, não existe a necessidade de tratar isso, existem poucas palavras na lingua portuguesa que possa ocasionar esse erro. A maior palavra da nossa lingua por exemplo é Pneumoultramicroscopicossilicovulcanoconiose, no caso acredito que não será utilizada no contexto de transito 😄 . Então Acho desnecessário o tratamento disso também.
