### ISSUE TITLE
Validação de tempo de ciclo - planos

### ISSUE THREAD

**Issue by pauloFernandes** [influunt/influunt#1403]
Quando a soma dos estágios excede o ciclo, o Influunt poderia dizer em quantos segundos o ciclo está sendo

superado. Outra coisa: na barra de erro, atualmente ele sempre indica o valor de “30 s” como o tempo de ciclo que está 

sendo superado, seja qual for o ciclo em programação (Ager);

**Comment by pauloFernandes** [comment]
Remover o texto de validação de "a soma dos tempos..." assim que o usuário alterar alguma informacao do plano

**Comment by leonardoherbert** [comment]
@ppires esse ticket já foi resolvido? 
@JuarezLustosa já tem cucumber para esse problema?

**Comment by JuarezLustosa** [comment]
@leonardoherbert  

A validação 30 s sempre aparecendo já está resolvida e possui teste para ela
