### ISSUE TITLE
Erro em planos, ao configurar estágio dispensável. 

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1429]
Em plano ao configurar um estágio como dispensável e salvar, quando finalizar o controlador e voltar nesse plano para edita-lo , o campo ESTÁGIO QUE RECEBE TEMPO DO ESTÁGIO DISPENSÁVEL volta em branco, perdendo assim a informação de qual estágio recebe o tempo. 
![captura de tela 2016-11-18 as 11 09 56](https://cloud.githubusercontent.com/assets/505372/20431138/97e9e0c4-ad7f-11e6-9bb8-10e184394da3.png)

**Comment by leonardoherbert** [comment]
@JuarezLustosa fazer um teste no cucumber, pois não consegui simular. Somente com controladores antigos, com novos controladores o problema não aconteceu.

**Comment by JuarezLustosa** [comment]
@leonardoherbert ok pode deixar esse bug comigo
