### ISSUE TITLE
Botão sincronizar em planos aparecendo no footer

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1522]
Na tela de planos, o botão de sincronizar está aparecendo no footer da página, abaixo do logo da raro:
![screen shot 2016-12-05 at 12 09 41](https://cloud.githubusercontent.com/assets/194442/20887945/e03ac69c-bae3-11e6-9ac2-b069d96bc172.png)

**Comment by leonardoherbert** [comment]
Isso ocorre também na tela de simulação
