### ISSUE TITLE
Evento de remoção de falha não veio 

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1564]
Ao causar falha de fase vermelha apagada, o painel de monitoramento acusou a falha. Quando a falha foi removida, o painel de facilidades não acusou a recuperação da falha (a tomada continuou vermelha). Provavelmente o evento de remoção de falha não foi enviado.

**Comment by leonardoherbert** [comment]
Havia um erro na api o @rodrigosol corrigiu, mais vale a pena testar todos os alarme e remoção de alarmes
