### ISSUE TITLE
Campos de hora preenchidos tela de tabela horária

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1577]
Enviado por: Bruno
> Campo dos segundos apresenta-se com preenchimento, inicial e os demais não.

![screen shot 2016-12-09 at 17 01 56](https://cloud.githubusercontent.com/assets/194442/21060953/589286a2-be31-11e6-86b1-2fea2457408f.png)

**Comment by leonardoherbert** [comment]
Foi solicitado que o segundos tivesse o valor 0 como default.
