### ISSUE TITLE
Erro com imagem dos estágios e croqui

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1579]
Enviado por: Ager
> Tentamos colar as figuras com os estágios no formato DWG (CAD) e não conseguimos. Pareceu-nos que a colagem dos croquis dos estágios e dos cruzamentos ficou mais lenta (provável problema com a rede ou alteração no software?)

**Comment by leonardoherbert** [comment]
Não é permitido salvar imagens do formata DWG somente Imagem.

**Comment by leonardoherbert** [comment]
@JuarezLustosa subir uma imagem com formato DWG e verificar se aparece a mensagem de erro.
