### ISSUE TITLE
Melhorar mensagem tela entre-verdes

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1580]
Enviado por: Ager
> Na tela de entreverdes, há um campo “intermitente ou apagado”. Para que serve? Não entendemos do que se trata.

**Comment by leonardoherbert** [comment]
Se trata do campo referente ao item 4.5.2.7, onde o usuário deve selecionar qual entreverdes ele quer utilizar para as transições para os modos amarelo intermitente/apagado.
