### ISSUE TITLE
Verificar dados salvos no wizard

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1581]
Enviado por: Ager
> Ao final de uma programação, precisamos retornar para alterar um tempo na tela de atraso de grupo semafórico. Para avançar, precisamos redigitar telas que já estavam preenchidas (por exemplo, o tempo do detetor ativo / inativo). Sugerimos que não seja necessário redigitar tais campos.
> Também, ao alterar uma configuração de um anel (operar ou não no modo manual), tivemos que redigitar/confirmar algumas páginas.

**Comment by ppires** [comment]
O problema é entendimento do uso so sistema. Vamos implementar uma opção no wizard "Salvar e Voltar p/ Resumo" sempre que o controlador esteja pronto para ser finalizado.

**Comment by leonardoherbert** [comment]
Vamos explicar o funcionamento atual, pois não precisa passar por todas as telas sempre. E se for adicionado um botão ficará mais confuso.
