### ISSUE TITLE
Erro ao cadastrar subárea

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1589]
Enviado por: Suely
> Dúvida: É necessário existir um controlador cadastrado para poder criar uma subárea a ele associado. É isso? O sistema só cria uma subárea se associar antes um controlador a ela. A hierarquia não deveria ser Cidade – Área – Subárea?

**Comment by leonardoherbert** [comment]
Hoje você pode adicionar um controlador a uma subárea durante a criação do controlador ou após criar uma subárea adicionar um novo controlador a ela. Pode remover a segunda opção deixar somente durante a criação do controlador.

**Comment by pauloFernandes** [comment]
duplica
