### ISSUE TITLE
Confirmação "nada a preencher" atraso de grupo

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1592]
enviado por: Suely
> Na tela de atraso de grupos, é obrigatório o preenchimento do campo “confirmo que não há configurações a fazer neste anel”? Qual é a consistência que o sistema está fazendo: por tela por transição de grupo ou por anel? Ele só deixou sair quando acionou o botão na primeira tela de cada anel, mesmo tendo atrasos configurados para um grupo deste anel.

**Comment by pauloFernandes** [comment]
@JuarezLustosa, favor fazer os testes cucumber.

**Comment by JuarezLustosa** [comment]
Teste realizado na issue #1588
