### ISSUE TITLE
Validação estágio demanda prioritária

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1596]
Enviado por: Suely
> Dúvida: No caso de estágio prioritário acho que o mesmo não pode ser um anel separado. Não consegui entender como seria neste caso talvez tenha que tem que estar dentro de um anel com outros estágios. Ele apontou um erro, mas não disse qual talvez por ter somente um estágio.
![screen shot 2016-12-09 at 17 39 50](https://cloud.githubusercontent.com/assets/194442/21062126/8616d72c-be36-11e6-979a-ca4347aab7cd.png)

**Comment by leonardoherbert** [comment]
Está habilitado para esse estágio o tempo máximo de permanência de 127segundos e o tempo de verde é de 128segundos o sistema apresentou o seguinte erro: "O tempo de estagio ultrapassa o tempo máximo de permanência."

Acho que nesse caso o monitoramento de tempo máximo de estágio deve ser suprimido.
