### ISSUE TITLE
/app/subareas

### ISSUE THREAD

**Issue by lucianocesar** [influunt/influunt#1649]
Os controladores associados nãoa parecem para alteração. Na visualização aparecem normalmente.

**Comment by pauloFernandes** [comment]
@lucianocesar,

O campo de **ASSOCIAR CONTROLADORES** não é uma lista de controladores que estão associados à determinada subárea. Ele é um "atalho" para associar a subárea recém-criada a diversos controladores que não possuem subáreas. Não é esperado que apareçam valores neste campo em um momento de edição deste formulário.
