### ISSUE TITLE
O campo "Nome", da Cidade, por ser único, deve ser obrigatório.

### ISSUE THREAD

**Issue by lucianocesar** [influunt/influunt#166]
O campo "Nome", da Cidade, por ser único, deve ser obrigatório.

**Comment by rodrigosol** [comment]
Podem existir duas cidades em estados diferentes com o mesmo nome. O ideal seria ter o modelo estado, porem como cidade aqui tem um contexto diferente de um cidade geografica, vou tornar apenas obrigatório a preenchimento do nome.
