### ISSUE TITLE
Bug em pesquisa na tela de comandos da central

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1710]
Ao tentar realizar uma pesquisa na index de comandos da central o sistema está apresentando erro 
![captura de tela 2016-12-20 as 10 28 56](https://cloud.githubusercontent.com/assets/505372/21350572/243a40cc-c69f-11e6-87b4-a4a3e28e664e.png)

**Comment by leonardoherbert** [comment]
@JuarezLustosa já esta ajustado no PR #1757 roda um cucumber para garantir
