### ISSUE TITLE
Erro validação plano manual

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1712]
Enviado por: Ager
>a) Aquela mensagem “este plano deve ter a mesma quantidade de estágios” voltou a aparecer, mas mesmo assim, conseguimos configurá-lo.

>b) Após a configuração deste plano da operação manual, fomos gravar o plano 1. O software, sozinho, incluiu um estágio (vejam o print da tela). Não conseguimos apaga-lo, o que ocorreu automaticamente, após avançarmos telas.

![screen shot 2016-12-20 at 11 39 31](https://cloud.githubusercontent.com/assets/194442/21352525/05d47e7c-c6a9-11e6-93bc-933bf5013d20.png)

**Comment by leonardoherbert** [comment]
@JuarezLustosa fazer um cucumber para esse caso
