### ISSUE TITLE
Atraso de grupo automático

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1717]
Enviado por: Ager

>O grupo semafórico de pedestres, quando paralelo a um grupo veicular, continua entrando em instante errado.

>a) ERRADO:
![screen shot 2016-12-20 at 11 47 42](https://cloud.githubusercontent.com/assets/194442/21352765/2ab9e708-c6aa-11e6-9d18-8c79cbbddfb2.png)

>b) CORRETO (o software devewria fazer isto)
![screen shot 2016-12-20 at 11 48 09](https://cloud.githubusercontent.com/assets/194442/21352784/40147e92-c6aa-11e6-972a-ce1846209a30.png)

**Comment by leonardoherbert** [comment]
issue #1587
