### ISSUE TITLE
Atraso de grupo automático (Vincenzo)

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1719]
Enviado por: Vincenzo

>Foi inserido um pedestre G6 carona do G1, no Anel 1, do cruzamento Emilia Marengo x Francisco Marengo.
>Na transição de G1 e G6 para G2, temos:
>- valor de entreverdes do G1 é de 5 segundos;
>- valor de entreverdes do G6 é de 10 segundos;

>O G6 deve, nesse caso, iniciar o piscante vermelho 5 segundos antes do início do amarelo de G1; Da maneira apresentada (vide print anexo), ele inicia o entreverdes de G6 carona NO MESMO INSTANTE que inicia o entreverdes de G1, causando um vermelho TOTAL (LIMPEZA) de 7 segundos antes do inicio de G2 (fase conflitante com G1).

>_Observação: É o mesmo problema levantado pelo Ager (ver o item 07 deste Relatório). É o mesmo problema apontado no item 13 do Relatório ”SUGESTÕES E COMENTÁRIOS SOBRE INFLUUNT – SEXTO MÓDULO VERSÃO 1.1 – TESTES REALIZADOS EM 08/12/2016” e que foi objeto do e-mail encaminhado em 13/12/2016: deve ser implementado conforme o item 4.5.2.8 da Especificação._

![screen shot 2016-12-20 at 11 54 29](https://cloud.githubusercontent.com/assets/194442/21352987/194de0e0-c6ab-11e6-9c76-b19392ecd8c5.png)

**Comment by leonardoherbert** [comment]
issue #1587
