### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by lucianocesar** [influunt/influunt#172]
1) Na tela "/app/fabricantes/new" O Drop/Down da Configuração não abre quando a tela está reduzida.
2) Layout quebra em diversos lugares quando diminui. Tela de cadastro de Fabricantes, Aneis do Controlador, Associação (esse quebra sempre).

**Comment by pauloFernandes** [comment]
* Problema no select dos formulários de fabricantes corrigido.
* Os problemas de layout dos controladores foi movido para a issue #192, por necessitar de análise de UC
