### ISSUE TITLE
Observação grupo semafórico

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1720]
Enviado por: Vincenzo

>A inserção de novo grupo no Anel 1 (existindo outras fases nos demais anéis) fez com o sistema renumerasse todas as fases NA SEQUENCIA; Em reunião com o Sun, Cucci, Ager e o Bruno, chegou-se à conclusão que não tem problema (tratar-se- ia de um projeto novo, com nova numeração de grupos, tendo apenas um pequeno retrabalho de ligação das mesmas nas borneiras, como já é feito hoje). 

>Observação: A solução implementada pela Raro está correta.

**Comment by rodrigosol** [comment]
ok
