### ISSUE TITLE
Atraso de grupo automático (Madeira)

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1722]
Enviado por: Madeira

>**Permanece um erro grave:** os entreverdes dos grupos que fecham simultaneamente, com tempos diferentes, estão iniciando o entreverdes ao mesmo tempo. O correto é que terminem juntos. Ou seja, os grupos com tempo total de entreverdes maior devem começar o fechamento com antecedência para terminarem juntos.

**Comment by leonardoherbert** [comment]
issue #1587
