### ISSUE TITLE
Confirmação nada a preencher transições proibidas

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1728]
Enviado por: Bruno

![screen shot 2016-12-20 at 12 02 37](https://cloud.githubusercontent.com/assets/194442/21353255/56b35f7c-c6ac-11e6-93bd-4550e938b739.png)

**Comment by leonardoherbert** [comment]
A confirmação só aparecerá em lugares onde nada foi feito, por isso é necessário que o usuário confirme que nada será feito nessa tela para avançar.
