### ISSUE TITLE
Dúvida confirmação nada a preencher atraso de grupo

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1735]
Enviado por: Suely

>Na tela de atraso de grupos, é obrigatório o preenchimento do campo “confirmo que não há configurações a fazer neste anel”? Qual é a consistência que o sistema está fazendo: por tela, por transição de grupo ou por anel? Ele só deixou sair quando acionou o botão na primeira tela de cada anel, mesmo tendo atrasos configurados para um grupo deste anel. Esta dúvida persiste ainda nesta versão!

**Comment by rodrigosol** [comment]
Verificar

**Comment by leonardoherbert** [comment]
@JuarezLustosa criar um cucumber que verifica todos os cenários dessa marcação do check
