### ISSUE TITLE
Erro diagrama de intervalos

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#1747]
Na tela de planos, caso exista um estágio associado a somente um grupo semafórico, este grupo semafórico não pode ser desativado. No exemplo abaixo, o grupo G6 não pode ser desativado, pois somente ele fica verde no estágio E2.
![screen shot 2016-12-20 at 18 59 17](https://cloud.githubusercontent.com/assets/194442/21367744/72d8f92a-c6e6-11e6-840b-467a09ecf140.png)

**Comment by leonardoherbert** [comment]
Como a programação não está errada e sim, pensamos que seja uma programação _"estranha"_ mas como não sabemos se essa possibilidade existe em algum caso, nada será feito.
