### ISSUE TITLE
Bug Tabela EntreVerde - Ao tentar adicionar uma nova tabela entre verdes o sistema não  está comportando  corretamente. Não é possível configurar

### ISSUE THREAD

**Issue by JuarezLustosa** [influunt/influunt#1819]

**Comment by leonardoherbert** [comment]
Problema ao clicar em cima do label. Fora do label funciona normalmente.

![image](https://cloud.githubusercontent.com/assets/1890706/22121402/0625988c-de6b-11e6-9941-f3880f1129ba.png)
