### ISSUE TITLE
Limpar a tela de ler dados antes de receber novas informações

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#1852]

**Comment by leonardoherbert** [comment]
1- Limpar os dados da tela de ler dados
2- Colocar um load até que receba a resposta do controlador ou ocorra o timeout
3- Ajustar o icone do `X` quando ocorre falha no envio de dados.

**Comment by ppires** [comment]
Imporconfig.codigoFalha está sem tradução (I18n)
