### ISSUE TITLE
Verificar esse caso

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#1912]
1. Criando um novo agrupamento (no caso denominado “SUBSANTOS”), e ao relacionar os controladores, o sistema só listou dois dos três controladores. Nesta subárea existem três controladores com dez anéis para serem selecionados ou não.

![image](https://cloud.githubusercontent.com/assets/1890706/22157805/56de054c-df20-11e6-90d7-73db3d7a36dd.png)

**Comment by ppires** [comment]
Ao criar um agrupamento não são listados os controladores com status "Em configuração" ou "Arquivado".
