### ISSUE TITLE
Problema ao buscar uma rua

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#1924]
Em relação à falha levantada, o problema não ocorreu, no entanto, ao tentar cadastrar um determinado logradouro, - Av. Brasil – o sistema não localizou, não sabemos se é um problema do sistema ou da interface com o mapa, mas fica o registro do problema encontrado.

**Comment by pauloFernandes** [comment]
A ferramenta de pesquisa de endereços do Google, que é utilizada para compor o campo de localizações de endereços do controlador no Influunt, não possui, por algum motivo, o endereço da Avenida Brasil de São Paulo. O único endereço encontrado pelo sistema é uma empresa com este mesmo nome.

Já reportamos ao Google o problema, e estamos aguardando resposta de sua equipe quanto ao problema.

Enquanto o problema não é resolvido, sugerimos a pesquisa de um endereço próximo ao local desejado. Encontrado o local, arrastar o marcados no mapa até a posição desejada. Após isso, o endereço dos logradouros podem ser editados.
