### ISSUE TITLE
Pagina Anéis

### ISSUE THREAD

**Issue by nathanraro** [influunt/influunt#240]
- Remover seção de Breadcumbs 
- Atualizar tamanho do Wizard (títulos com 13px)
- Botão de Próximo abaixo do card principal, alinhado á direita
- Adicionar título
- Campo de Endereço precisa vir antes de Localização
- Centralizar Item selecionado na lista (menu lateral esquerdo - seleção de anéis)
- Menu de Estágios: Aumentar Thumbnail
- Menu de Estágios: Exibir nome do arquivo sem Hover

![aneis-v4](https://cloud.githubusercontent.com/assets/19826047/16929174/eaa79546-4d0c-11e6-9ad9-20c72ba13064.jpg)

**Comment by dantemarchi** [comment]
Reaberto para correção da área de upload

**Comment by dantemarchi** [comment]
resolvido
