### ISSUE TITLE
Pagina Dados Básicos

### ISSUE THREAD

**Issue by nathanraro** [influunt/influunt#247]
- Remover seção de Breadcumbs 
- Atualizar tamanho do Wizard (títulos com 13px)
- Botões de Próximo/Anterior abaixo do card principal, alinhado á direita
- Campo "Pesquisar por Endereço" deve vir antes do mapa
![dadosbasicos-v4](https://cloud.githubusercontent.com/assets/19826047/16930216/8b18aeee-4d11-11e6-90a3-3679a42e8de2.jpg)

**Comment by leonardoherbert** [comment]
Não foi removido o Breadcumbs pois não tinha nenhum identificação da pagina Controlador.
