### ISSUE TITLE
Validação de EF - Documento Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by sergioalvesdasilva** [influunt/influunt#254]
Favor inserir a numeração dos casos de uso no nome dos casos de uso do documento de Diagrama de Casos de Uso. 
Se possível utilizar label para identificar as setas como include ou extend entre os casos de uso.

**Comment by lucianocesar** [comment]
Solicitação realizada com sucesso.

**Comment by leonardoherbert** [comment]
@sergioalvesdasilva , já finalizamos essa issue. Senão o que está dependente?
