### ISSUE TITLE
Validação de EF - UC005 - Manter Usuários - v1.0

### ISSUE THREAD

**Issue by sergioalvesdasilva** [influunt/influunt#259]
Coloquei o documento em modo de revisão e fiz minhas considerações no documento. 
Se estiver de acordo é só clicar na opção Aceitar dentro da seção de revisão do documento word. 
[P11 - UC005 - Manter Usuários - v1.0.docx](https://github.com/influunt/influunt/files/372007/P11.-.UC005.-.Manter.Usuarios.-.v1.0.docx)

**Comment by lucianocesar** [comment]
Observações aceitas e texto ajustado conforme orientação.
