### ISSUE TITLE
Validação de EF - UC014 - Manter Configurações - v1.0

### ISSUE THREAD

**Issue by sergioalvesdasilva** [influunt/influunt#263]
Coloquei o documento em modo de revisão e fiz minhas considerações no documento. 
Se estiver de acordo é só clicar na opção Aceitar dentro da seção de revisão do documento word. 
[P11 - UC014 - Manter Configurações - v1.0.docx](https://github.com/influunt/influunt/files/372052/P11.-.UC014.-.Manter.Configuracoes.-.v1.0.docx)

**Comment by lucianocesar** [comment]
Observações aceitas e texto ajustado conforme orientação.
