### ISSUE TITLE
Validação de EF - UC017 - Manter Controladores - v1.0

### ISSUE THREAD

**Issue by sergioalvesdasilva** [influunt/influunt#266]
Coloquei o documento em modo de revisão e fiz minhas considerações no documento. 
Se estiver de acordo é só clicar na opção Aceitar dentro da seção de revisão do documento word. 
[P11 - UC017 - Manter Controladores - v1.0.docx](https://github.com/influunt/influunt/files/372083/P11.-.UC017.-.Manter.Controladores.-.v1.0.docx)

**Comment by lucianocesar** [comment]
Observações aceitas e texto ajustado conforme orientação.
Foi acrescentada observação sobre as regras de negócio para validação do controlador, que estão sendo implementadas e serão mencionadas na próxima iteração.
