### ISSUE TITLE
Validação EF - Especificação de Interfaces

### ISSUE THREAD

**Issue by sergioalvesdasilva** [influunt/influunt#267]
"Este documento tem por finalidade fornecer uma visão da necessidade de obtenção e fornecimento de dados e serviços externos a aplicação. Ele deve apresentar os fluxos de informação que entram e saem da fronteira da aplicação para se comunicarem com outros sistemas ou componentes externos."

O documento produzido está mapeando interfaces de fluxos de informação internos a aplicação, não externos a aplicação.

Só preciso saber quais serviços serão consumidos de outros sistemas e quais serviços devem ser providos por outros sistemas.

**Comment by lucianocesar** [comment]
Foi inserida a informação dos serviços previstos. No entanto, como ainda não foram identificados quais estes serviços e as funcionalidades, foi acrescentada a informação da previsão das iterações nas quais essa identificação ocorrerá.
