### ISSUE TITLE
Validação Casos de Teste - UC004 - Manter Perfis

### ISSUE THREAD

**Issue by sergioalvesdasilva** [influunt/influunt#269]
No documento disponibilizado no SVN (http://201.47.97.194:81/svn/mobilab/01%20Projetos/01%20Edital%20SMT%2001-2015/P11/03%20Construcao/01%20Codigo%20Fonte/Index.html) não encontrei casos de teste para o respectivo caso de uso.

**Comment by ppires** [comment]
@sergioalvesdasilva: implementamos os casos de teste para o caso de uso, e fizemos o upload para o SVN.
