### ISSUE TITLE
Melhorar as mensagens de erro no sistema

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#278]
As mensagens de erro devem ser mais chamativas. Sugestão: letra, em preto ou
em vermelho, em negrito, com fonte maior do que o restante do texto, contra
um fundo branco.

**Comment by dantemarchi** [comment]
Coloquei uma sugestão mais chamativa, fundo vermelho, fonte negrito branca.
![captura de tela 2016-07-20 as 19 55 31](https://cloud.githubusercontent.com/assets/1928821/17005968/f638f154-4eb3-11e6-865d-ee622a7da697.png)

**Comment by dantemarchi** [comment]
feito
