### ISSUE TITLE
Adicionar nova página ao Wizard

### ISSUE THREAD

**Issue by nathanraro** [influunt/influunt#321]
![wizard](https://cloud.githubusercontent.com/assets/19826047/17069701/621c68e4-502e-11e6-9067-e91cb3a5c2ba.jpg)

**Comment by dantemarchi** [comment]
Criei o menu novo, atualizei botões próximo e anterior, mas a página não foi possível visualizar, (ou não soube configurar direito) para continuar trabalhando, da erro. Branch front#iss321 @lesio

**Comment by dantemarchi** [comment]
feito
