### ISSUE TITLE
Criar tela - Configuração Grupo

### ISSUE THREAD

**Issue by nathanraro** [influunt/influunt#322]
![config grupo semaf-v2](https://cloud.githubusercontent.com/assets/19826047/17069807/f97663e8-502e-11e6-9266-e52b17f5fca2.jpg)

JPG e PSD também no Google Drive: https://drive.google.com/a/rarolabs.com.br/folderview?id=0B7VSj7jLyKjvdWtlLUl5OFFoWUk&usp=sharing

**Comment by dantemarchi** [comment]
feito
