### ISSUE TITLE
Navegação em abas nas demais telas

### ISSUE THREAD

**Issue by dantemarchi** [influunt/influunt#361]
Aplicar navegação em abas nas telas que contém anéis, substituindo a navegação atual.

**Comment by leonardoherbert** [comment]
Após a alteração verificar as mensagens de erro que não estão aparecendo.
![screen shot 2016-07-28 at 16 10 32](https://cloud.githubusercontent.com/assets/1890706/17226065/fc36a90e-54dd-11e6-950b-fe561b514e92.png)
