### ISSUE TITLE
Botão Quebrando em Planos

### ISSUE THREAD

**Issue by lucianocesar** [influunt/influunt#366]
- Botão Próximo não está funcionando;
- Layout dos botões está quebrando, na tela de Planos.
![image](https://cloud.githubusercontent.com/assets/5081549/17215208/7dac1d06-54b2-11e6-906a-5363aac5dbdb.png)

**Comment by leonardoherbert** [comment]
Ajustar o novo layout de abas, colocar uma forma de identificar os blocos.

1- Colocar um botão abaixo da imagem de estágios que abrira um modal com as configurações do ultimo bloco.

Segue a imagem do plano atual
![plano](https://cloud.githubusercontent.com/assets/1890706/17264205/d23c06ec-55bb-11e6-8936-face54377b94.png)

**Comment by dantemarchi** [comment]
Aplicado versão com abas
