### ISSUE TITLE
implementar atraso de grupo vermelho

### ISSUE THREAD

**Issue by pauloFernandes** [influunt/influunt#403]
implementar atraso de grupo vermelho

**Comment by leonardoherbert** [comment]
Resumi os diagramas enviados pela Suely em dois casos, conforme os exemplos das figuras abaixo.
 
O primeiro caso é o atraso da perda do direito de passagem e o segundo caso é o atraso do ganho do direito de passagem.
 
Dessa forma, não é necessária a criação de dois campos, como havia pensado o Leo. O atraso estará definido se for definido o grupo e a transição, após ter sido definido que grupo anda em cada estágio (associação grupo x estágio). De fato:
 
Se o grupo que será atrasado andar no estágio anterior da transição teremos o caso de atraso da perda do direito de passagem.
 
Se o grupo que será atrasado andar no estágio posterior da transição teremos o caso de atraso do ganho do direito de passagem.
 
Acho que a solução é configurar o atraso de grupo de forma independente da associação grupo x estágio (com todos os grupos configurados para o anel, independentemente do estágio em que anda). A única condição é que associação grupo x estágio deverá ser feita previamente.
![image004](https://cloud.githubusercontent.com/assets/1890706/17435493/a49cef86-5ae7-11e6-9229-7fbbd2e18c15.jpg)
![image005](https://cloud.githubusercontent.com/assets/1890706/17435492/a46508e6-5ae7-11e6-9ab8-0e4dd02092fe.jpg)
