### ISSUE TITLE
Ajustes em layouts

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#418]
1- Drag Drop somente na primeira coluna (Assoaciação Estagio x Grupo Semaforico)
2- Ajustar tela de transições proibidas
   2.1- Imagens superior
   2.2- Separar em blocos
3- Delimitar as imagens do estagio e colocar o titulo do estagio fora da imagem (Tabela Entre-Verdes)
4- Colocar a configuração de monitoramento do detector em um modal (Associação de detectores)
5- Verificar o tamanho das imagens em todos os lugares. (Em alguns caso esta quebrando o layout)

**Comment by dantemarchi** [comment]
Apenas faltou resolver o item 1
