### ISSUE TITLE
interface de mapa todos controladores

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#483]

**Comment by leonardoherbert** [comment]
Visualizar a tabela horária no controlador
Visualizar o resumo geral do controlador
Visualizar o diagrama de intervalos, croqui e a sequencia de estágios nos aneis
Mostrar planos configurados
Visualizar as redes no mapa (Parecido com o power point)
Botão esquerdo do mouse mostrar as informações
Botão direito do mouse mostrar as possíveis ações
Filtros por modo
Controladores com Falhas

**Comment by nathanraro** [comment]
Ações: Impor planos, trocar tabela horária, enviar planos, enviar tabela horário, outras opções

**Comment by nathanraro** [comment]
![mapadoscontroladores-v3_dir](https://cloud.githubusercontent.com/assets/19826047/18213735/1d4a73f6-7120-11e6-8d12-4599e51c5bf1.jpg)
![Uploading MapadosControladores-v3_esq.jpg…]()

**Comment by nathanraro** [comment]
![mapadoscontroladores-v3_dir_1](https://cloud.githubusercontent.com/assets/19826047/18213790/4ddf9352-7120-11e6-917f-7b6527ed93be.jpg)
