### ISSUE TITLE
Tooltip não funcionada corretamente em stage/production

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#529]

**Comment by leonardoherbert** [comment]
Parece que é em algumas tela, por exemplo dados basicos o botão avançar. Pode ser que o tooltip não foi inserido nessa tela, se for isso verificar todos os tooltips do sistema

**Comment by dantemarchi** [comment]
Paulo o novo tooltip que fizemos aquele dia estava dentro do branch i18n, quando surgiu a necessidade de trocar, o atual é aquele incompatível com o i18n. Vou desmembrar e mandar a correção.
