### ISSUE TITLE
Criar a tela de modelo de controlador

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#556]
1- Remover a criação de modelo na tela de fabricante.
2- Criar a tela de modelo de controlador.
3- Colocar os limites. (Deverá ser campo digitavel e não utilizar o relogio)
4- Voltar com a configuração de modelo do controlador para dentro do modelo (as configurações foram movidas na última iteração para a tela de dados básicos do controlador)

**Comment by pauloFernandes** [comment]
- Remover os knobs de configurações do modelo de controlador utilizado. Devemos voltar ao conceito de configurações dos modelos, que deverá ser feita no cadastro dos modelos. Na tela de dados básicos, devemos somente exibir as configurações, conforme era feito no primeiro layout executado.
