### ISSUE TITLE
Checkbox de confirmação de preenchimento de dados

### ISSUE THREAD

**Issue by pauloFernandes** [influunt/influunt#570]
- Para as telas do wizard onde é possível que o usuário continue sem preencher nada (ex.: na tela de transições proibidas) deverá se criado um checkbox onde o usuário afirma que "passei por esta tela e não há configurações a ser feitas aqui". Não será possível continuar para a tela seguinte caso este checkbox não tenha sido ativado ou o usuário não preencheu os dados.

**Comment by nathanraro** [comment]
![estagios-v4](https://cloud.githubusercontent.com/assets/19826047/17869486/d854793e-6889-11e6-8861-6e78e687abf1.jpg)

Botões de "Próximo" devem ficar desabilitados até que o usuário faça alguma configuração ou clique no checkbox.
