### ISSUE TITLE
Cadastro de detectores

### ISSUE THREAD

**Issue by pauloFernandes** [influunt/influunt#571]
- Na associação de detectores, somente devem aparecer as opções de tipos de detectores dos tipos de grupos criados anteriormente. Ex.: Dado que o usuário configurou o controlador somente com grupos veiculares, a tela de controladores não deverá exibir a opção de criar detectores de pedestres

**Comment by pauloFernandes** [comment]
- No popup de configurações dos detectores: Deverão existir somente dois campos, ausência de detecção ou detecção permanente. Os **knobs** deverão ser preenchidos com unidades em **minutos** (atualmente está em segundos).

**Comment by pauloFernandes** [comment]
- Na tabela de associação dos detectores com os grupos, devemos colocar um checkbox no meio de cada celula da tabela. Desta forma, o usuário não deverá mais clicar na célula para associar o detector ao anel, mas sim marcar o checkbox.

**Comment by leonardoherbert** [comment]
os tempos de permanência para alarmes dos detectores devem ser revistos: são apenas dois alarmes, tanto para veicular como para pedestre: ausência de detecção ou detecção permanente. Esses tempos são longos, de modo que os limites de tempo devem ser configurados em minutos, mão em segundos
Os valores minimos e máximos são somente da especificação dos limites do controlador. A configuração do contrlador deverá armazenar somente um valor para os tempos de ausencia
