### ISSUE TITLE
Resolver a mensagem vermelha que não deve aparecer para o usuário do sistema.

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#572]
![untitled](https://cloud.githubusercontent.com/assets/1890706/17789116/1cee0478-6567-11e6-85b4-fbf60a70c451.png)
![untitled2](https://cloud.githubusercontent.com/assets/1890706/17789117/1d2178d0-6567-11e6-9949-25ff251d39ea.png)

**Comment by pauloFernandes** [comment]
Esta mensagem de erro não deve ser exibida. Somente o warn ação não autorizada. Sugiro que a api da diretiva de toast seja alterada para que se o aplicativo estiver em modo de produção, as mensagens do tipo error não sejam exibidas.
