### ISSUE TITLE
Bug indicador de progresso wizard

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#581]
Está ocorrendo um erro intermitente no mostrador de progresso do wizard. Em alguns momentos o passo do wizard que acabou de ser feito fica cinza, como se ainda não tivesse sido configurado. Comigo aconteceu entre os passos "Grupos Semaforicos" e "Verdes Conflitantes". Com o @lesio aconteceu entre os passos "Detectores" e "Revisão". Ao dar um reload na página o problema some.
![screen shot 2016-08-19 at 15 22 45](https://cloud.githubusercontent.com/assets/194442/17820035/224f6442-6621-11e6-8a2b-a95994dc89d0.png)

**Comment by pauloFernandes** [comment]
Não ocorre mais.
