### ISSUE TITLE
Ajuste tela de revisão

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#592]
- Remover todos os "olhinhos" da tela (![screen shot 2016-08-22 at 10 52 43](https://cloud.githubusercontent.com/assets/194442/17857025/971ab3da-6856-11e6-93e5-efc1faed0c61.png))
- Layout quando não tiver dados cadastrados (ex: "Este controlador ainda não possui transições cadastradas").
- Layout das tabelas entre-verdes: podemos ter até 50 tabelas entre-verdes diferentes, e cada tabela entre-verdes pode ter um número variável de transições.

**Comment by nathanraro** [comment]
![revisao-v2-a](https://cloud.githubusercontent.com/assets/19826047/17872165/2e9406c4-6895-11e6-854d-3d7c1a006af6.jpg)
![revisao-v2-b](https://cloud.githubusercontent.com/assets/19826047/17872166/2e946f38-6895-11e6-9e32-a22a9d9a466a.jpg)
