### ISSUE TITLE
Tela de agrupamento de controladores

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#614]
1- O usuário deve selecionar areas e/ou controladores indivudalmente

**Comment by nathanraro** [comment]
Usuario pode escolher, Sub-areas, que ja vão retornar Controladores para facilitar a edição

**Comment by nathanraro** [comment]
![agrupamento-v2](https://cloud.githubusercontent.com/assets/19826047/17983902/48ddb276-6ae5-11e6-946f-b0aab896716c.jpg)
