### ISSUE TITLE
Abrir modal ao visualizar controlador

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#657]
Ao clicar no botão de "Visualizar" controlador na index de controladores, abrir o modal com a tela de revisão. Comportamento atual é redirecionar para o último passo do wizard.
![screen shot 2016-08-27 at 12 16 41](https://cloud.githubusercontent.com/assets/194442/18028257/5fe9ec3e-6c50-11e6-8d68-95851e294150.png)

**Comment by JuarezLustosa** [comment]
@ppires Quer que eu faça esse ?
