### ISSUE TITLE
Transições Proibidas

### ISSUE THREAD

**Issue by lucianocesar** [influunt/influunt#806]
Nas telas de transições proibidas e atraso de grupo, marquei que não tinha nada a ser feito, depois salvei voltando para a tela anterior. Quando avancei novamente a caixa estava marcada. Se eu voltei salvando não deveria ter ficado marcada?

**Comment by leonardoherbert** [comment]
Toda vez que você passar por essa tela, será necessário informar que nada será feito ou preencher e um modo de obrigar o usuário a dar uma verifica na tela
