### ISSUE TITLE
Tabela de Entre Verdes

### ISSUE THREAD

**Issue by lucianocesar** [influunt/influunt#808]
A tela de Tabela Entre Verdes deixa passar sem nenhuma alteração. Então não deveria ter a caixa para marcar como na de transações proibidas e atraso de grupo?

**Comment by leonardoherbert** [comment]
A marcação não é que você não fez nada, mas sim que não existe configuração para aquela tela. No caso da tabela entre verdes os valores já estão preenchidos como padrão.
