### ISSUE TITLE
15- Check transição proibida por anel

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#842]
É preciso separar por anel a configuração de transições proibidas. Hoje só está presente no anel 1. Também deveria haver um check-box por anel para informação de que não há transição proibida naquele caso.

**Comment by JuarezLustosa** [comment]
Resolvida em staging

**Comment by leonardoherbert** [comment]
Falta o check-box por anel, hoje esta unico para todos os aneis.
