### ISSUE TITLE
16- Ajustes valores monitoramento de falhas botoeiras

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#843]
No monitoramento de falha das botoeiras, favor estender o limite máximo para 3 dias (4.320 minutos), pois há casos em que não existem pedestres no fim de semana e isso evitaria alarmes desnecessários.

Observação: será alterado o item 4.5.23.2 da Especificação, alterando o valor de 1440 para 4320 minutos.

**Comment by JuarezLustosa** [comment]
Resolvi
