### ISSUE TITLE
18- Numeração de detectores

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#845]
Ainda na parte de detectores: a denominação de detectores deveria ser contínua, como é o caso de grupos semafóricos em relação aos anéis. Ou seja, se no anel 1 eu associei um detector de pedestres e ele recebeu o nome de “DP1”, caso eu configure outro detector em outo anel, ele seria o DP2 e assim por diante. Idem quanto ao veicular.

**Comment by JuarezLustosa** [comment]
Resolvi
