### ISSUE TITLE
19- Indicação de cruzamento

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#846]
A partir da tela inicial, seria melhor aparecer no alto de todas as telas (pode ser na faixa horizontal superior verde) o nome do cruzamento que se está editando.

**Comment by nathanraro** [comment]
![breadcrumb](https://cloud.githubusercontent.com/assets/19826047/18566211/5cbaa83c-7b69-11e6-8380-7fb8846236d9.jpg)

Também é interessante padronizarmos as distâncias acima e abaixo do texto - a margem abaixo do Breadcrumb está muito grande atualmente:
![screenshot 2016-09-15 17 26 23](https://cloud.githubusercontent.com/assets/19826047/18566307/bfbc73d4-7b69-11e6-8c7b-b5cc9d2a9ded.png)
