### ISSUE TITLE
32- Ajustes no valores de monitoramento de detectores

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#859]
No item detector de pedestres, o tempo máximo de permanência sem atuação deverá ser de 3 dias ou 4320 minutos, e para permanente atuação 1 dia ou 1440 minutos.

Observação: será alterado o item 4.5.23.2 da Especificação, alterando o valor de 1440 para 4320 minutos.

**Comment by JuarezLustosa** [comment]
resolvido
