### ISSUE TITLE
32- Erro não mostrar em planos

### ISSUE THREAD

**Issue by leonardoherbert** [influunt/influunt#877]
Erro: Desta vez foi possível configurar os três primeiros anéis, mas o quarto não, apesar dos tempos estarem corretos. Não foi possível saber qual era o erro, pois apenas apareceu o ícone sem explicação alguma.  Ao voltar, todas as informações dos outros anéis digitados sem erro se perderam.

**Comment by JuarezLustosa** [comment]
@leonardoherbert Essa issue foi resolvida na #923
