### ISSUE TITLE
Botão cortado tabela horária

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#929]
Os botões de salvar e descartar na tela de tabela horária estão cortados.
![screen shot 2016-09-21 at 00 44 46](https://cloud.githubusercontent.com/assets/194442/18697127/cf77adb4-7f94-11e6-9180-189fadb980cf.png)

**Comment by pauloFernandes** [comment]
Este problema parece ocorrer também em outras telas. Acho que precisaremos revisar todas elas.
