### ISSUE TITLE
Diagrama de intervalos com erro

### ISSUE THREAD

**Issue by ppires** [influunt/influunt#952]
Na configuração de planos, quando tem somente o mesmo estágio duplicado, o diagrama de intervaos fica com erro (não mostra nenhum dos tempos entre-verdes).
![screen shot 2016-09-22 at 17 10 16](https://cloud.githubusercontent.com/assets/194442/18764366/78255918-80e7-11e6-868a-e1e93cfa55bc.png)

**Comment by pauloFernandes** [comment]
@ppires: O diagrama está certo. Os entreverdes somente ocorrem quando durante a troca de estágio existem verdes conflitantes. No seu caso você configurou um estágio duplo onde não existem entreverdes em estágios iguais

**Comment by ppires** [comment]
👍
