### ISSUE TITLE
Simulador

### ISSUE THREAD

**Issue by rodrigosol** [influunt/influunt#996]

**Comment by ppires** [comment]
@rodrigosol, considerações do mobilab sobre o simulador da reunião em 07/10:
- separar diagrama por anel. Sugestões:
  - colocar um espaço (linha em branco) entre os grupos de anéis diferentes
  - colocar uma cor de fundo nos grupos semafóricos para cada anel
  - fazer a simulação com um anel só
- troca de planos ocorreu no momento errado. Plano só pode entrar em operação depois do entreverdes do plano antigo
